# Generated by Django 2.0.7 on 2019-06-22 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('tweet_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('createdat', models.DateField(blank=True, null=True)),
                ('tweet', models.CharField(blank=True, max_length=280, null=True)),
            ],
            options={
                'db_table': 'tweet',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('screenname', models.CharField(max_length=32)),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('protected', models.BooleanField()),
                ('verified', models.BooleanField()),
                ('followers', models.IntegerField()),
                ('friends', models.IntegerField()),
                ('listed', models.IntegerField()),
                ('favourites', models.IntegerField()),
                ('statuses', models.IntegerField()),
                ('createdat', models.DateTimeField(blank=True, null=True)),
                ('defaultacc', models.BooleanField()),
                ('hobby1', models.CharField(blank=True, max_length=32, null=True)),
                ('hobby2', models.CharField(blank=True, max_length=32, null=True)),
                ('isbrillentrager', models.BooleanField()),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='user1', serialize=False, to='polls.User')),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='user2', to='polls.User')),
                ('user1_retweettimes', models.IntegerField()),
                ('user2_retweettimes', models.IntegerField()),
                ('typeofrelationship', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'relationship',
                'managed': False,
            },
        ),
    ]
