# Generated by Django 2.0.7 on 2019-06-22 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Following',
            fields=[
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='follower', serialize=False, to='polls.User')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='user', to='polls.User')),
            ],
            options={
                'db_table': 'following',
                'managed': False,
            },
        ),
    ]
